const METAPLEX_CANDYMACHINE_PROGRAM =
  'cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ';
const METAPLEX_TOKEN_METADATA_PROGRAM =
  'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s';
const MAGIC_EDEN_ACCOUNT_ADDRESS =
  '2NZukH2TXpcuZP4htiuT8CFxcaQSWzkkR6kepSWnZ24Q';

export {
  METAPLEX_CANDYMACHINE_PROGRAM,
  METAPLEX_TOKEN_METADATA_PROGRAM,
  MAGIC_EDEN_ACCOUNT_ADDRESS,
};
